# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderit', '0002_auto_20170308_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
